### ISSUE TITLE
Confusing device icon

### ISSUE THREAD

**Issue by myrho** [Zinggi/NoKey#27]
Hi! 
Thanks for sharing this great tool!
I just tried it out. That's what my device list looks like:
![untitled](https://user-images.githubusercontent.com/1172181/41287996-08c53708-6e45-11e8-8d84-1739206e856a.png)

As you can see the device "Fairphone" has a "no entry" icon. Does this mean anything? Or is it just randomly chosen? Either way I think it needs clarification.

**Comment by Zinggi** [comment]
Hi, thanks for trying it out!
You were very unlucky with that icon, it's indeed randomly chosen.


Actually, the icon is derived from a randomly generated device ID using my [hash icon](http://package.elm-lang.org/packages/Zinggi/elm-hash-icon/latest) package.
The only way to change the icon is by getting a new ID, which you only get by resetting your device (in the settings).
Since you just started, you could reset your devices without any consequences until you get a more pleasant icon and pair them then.

The icon is actually meant as a security feature: If an attacker were to observe you while pairing, they could enter the code faster than you and you'd get paired with the attackers device. If the icon was configurable, the attacker could chose the same icon you're using and you wouldn't notice anything wrong. Since you can't change the icon, you would immediately notice that something went wrong, as the attackers device would almost certainly have a different icon.

I should probably add that to the FAQ, thanks for the question!
